<%@ Page Title="" Language="C#" MasterPageFile="~/Salary.Master" AutoEventWireup="true" CodeBehind="DeptDesigAndFinInstitution.aspx.cs" Inherits="NBU.PayBill.Salary.DeptDesigAndFinInstitution" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <script type="text/javascript">
        function clearTextBoxes() {
            for (i = 0; i < arguments.length; i++) {
                document.getElementById(arguments[i]).value = "";
            }
        }
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="BodyContent" runat="server">
    <div class="panel panel-default">
        <div class="panel-heading">Departments, Designation and Financial Institutions</div>
        <div class="panel-body">
            <div class="container" id="divShowDetails" runat="server">
                <div class="row">
                    <div class="col-md-4">
                        <div class="well well-sm">
                            <asp:Label ID="lblTitleDept" ClientIDMode="Static" CssClass="h4" runat="server" Text="Departments"></asp:Label>
                            <%--<asp:LinkButton runat="server" ID="lnkAddDept" ClientIDMode="Static" Text=" Add New" OnClick="lnkAddDept_Click"></asp:LinkButton>--%>
                            <a href="DeptDesigAndFinInstitution.aspx?TC=DT&ACT=ADD"><i class="fa fa-plus-square"></i></a>
                        </div>
                        <asp:GridView ID="gvDepartment" runat="server" AutoGenerateColumns="false" AutoGenerateSelectButton="false" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" BorderStyle="None" BorderWidth="0" CssClass="table table-hover" GridLines="None" SelectedRowStyle-BorderStyle="None" ShowHeader="False" CellPadding="0" Width="100%">
                            <RowStyle CssClass="row" HorizontalAlign="Left" VerticalAlign="Middle" />
                            <Columns>
                                <asp:TemplateField>
                                    <ItemTemplate>
                                        <asp:Label ID="lblDeptName" CssClass="col-10" runat="server" Text='<%# Eval("DepartmentName") %>'></asp:Label>
                                        <a href='DeptDesigAndFinInstitution.aspx?TC=DT&ACT=DEL&CD=<%# NBU.Common.Helper.StringUtil.Encode(Eval("DepartmentCD").ToString()) %>'><i class="fa fa-trash-alt"></i></a>
                                        <a href='DeptDesigAndFinInstitution.aspx?TC=DT&ACT=EDT&CD=<%# NBU.Common.Helper.StringUtil.Encode(Eval("DepartmentCD").ToString()) %>'><i class="fas fa-edit"></i></a>  
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                        </asp:GridView>
                    </div>
                    <div class="col-md-4">
                        <div class="well well-sm">
                            <asp:Label ID="lblTitleDesg" ClientIDMode="Static" CssClass="h4" runat="server" Text="Designations"></asp:Label>
                            <%--<asp:LinkButton runat="server" ID="lnkAddDesig" ClientIDMode="Static" Text=" Add New" OnClick="lnkAddDesig_Click" ></asp:LinkButton>--%>
                            <a href="DeptDesigAndFinInstitution.aspx?TC=DS&ACT=ADD"><i class="fa fa-plus-square"></i></a>
                        </div>
                        <asp:GridView ID="gvDesignation" runat="server" AutoGenerateColumns="false" AutoGenerateSelectButton="false" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" BorderStyle="None" BorderWidth="0" CssClass="table table-hover" GridLines="None" SelectedRowStyle-BorderStyle="None" ShowHeader="False" CellPadding="0" Width="100%">
                            <RowStyle CssClass="row" HorizontalAlign="Left" VerticalAlign="Middle" />
                            <Columns>
                                <asp:TemplateField>
                                    <ItemTemplate>
                                        <asp:Label ID="lblDesgName" runat="server" Text='<%# Eval("DesignationName") %>'></asp:Label>
                                        <a href='DeptDesigAndFinInstitution.aspx?TC=DS&ACT=DEL&CD=<%# NBU.Common.Helper.StringUtil.Encode(Eval("DesignationCD").ToString()) %>'><i class="fa fa-trash-alt"></i></a>
                                        <a href='DeptDesigAndFinInstitution.aspx?TC=DS&ACT=EDT&CD=<%# NBU.Common.Helper.StringUtil.Encode(Eval("DesignationCD").ToString()) %>'><i class="fas fa-edit"></i></a>  
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                        </asp:GridView>
                    </div>
                    <div class="col-md-4">
                        <div class="well well-sm">
                            <asp:Label ID="lblTitleFinInst" ClientIDMode="Static" CssClass="h4" runat="server" Text="Financial Institutions"></asp:Label>
                            <%--<asp:LinkButton runat="server" ID="lnkAddFI" ClientIDMode="Static" Text=" Add New" OnClick="lnkAddFI_Click"></asp:LinkButton>--%>
                            <a href="DeptDesigAndFinInstitution.aspx?TC=FI&ACT=ADD"><i class="fa fa-plus-square"></i></a>
                        </div>
                        <asp:GridView ID="gvFinInstitution" runat="server" AutoGenerateColumns="false" AutoGenerateSelectButton="false" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" BorderStyle="None" BorderWidth="0" CssClass="table table-hover" GridLines="None" SelectedRowStyle-BorderStyle="None" ShowHeader="False" CellPadding="0" Width="100%">
                            <RowStyle CssClass="row" HorizontalAlign="Left" VerticalAlign="Middle" />
                            <Columns>
                                <asp:TemplateField>
                                    <ItemTemplate>
                                        <asp:Label ID="lblFinInstitutionName" runat="server" Text='<%# Eval("FinancialInstitutionName") %>'></asp:Label>
                                        <a href='DeptDesigAndFinInstitution.aspx?TC=FI&ACT=DEL&CD=<%# NBU.Common.Helper.StringUtil.Encode(Eval("FinancialInstitutionCD").ToString()) %>'><i class="fa fa-trash-alt"></i></a>
                                        <a href='DeptDesigAndFinInstitution.aspx?TC=FI&ACT=EDT&CD=<%# NBU.Common.Helper.StringUtil.Encode(Eval("FinancialInstitutionCD").ToString()) %>'><i class="fas fa-edit"></i></a>  
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <%--<asp:TemplateField HeaderText="Address">
                                    <ItemTemplate>
                                        <asp:Label ID="lblFinInstitutionAddress" runat="server" Text='<%# Eval("FinancialInstitutionAddress") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>--%>
                            </Columns>
                        </asp:GridView>
                    </div>
                </div>
            </div>
            <div class="container" id="divDepartmentDetails" runat="server">
                <div class="row">
                    <div class="form-row">
                        <div class="form-group col-md-12 well well-sm">
                            <asp:Label ID="lbl_Dept_title" ClientIDMode="Static" CssClass="h3" runat="server" Text="Add New Department"></asp:Label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="txtDeptName">Name</label>
                            <asp:TextBox runat="server" ID="txtDeptName" ClientIDMode="Static" CssClass="form-control"></asp:TextBox>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="txtBankAcc">Bank Account Number</label>
                            <asp:TextBox runat="server" ID="txtBankAcc" ClientIDMode="Static" CssClass="form-control"></asp:TextBox>

                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <asp:Button ID="btnAddDept" runat="server" CssClass="btn btn-block btn-success text-center" PostBackUrl="~/DeptDesigAndFinInstitution.aspx" OnClick="btnAddDept_Click" Text="Submit" />
                        </div>
                        <div class="form-group col-md-2">
                            <asp:Button ID="btnDeptClear" OnClientClick="clearTextBoxes('txtDeptName','txtBankAcc')" CssClass="btn btn-secondary btn-block text-center" ClientIDMode="Static" runat="server" Text="Clear" />
                        </div>
                        <div class="form-group col-md-2">
                            <a href="DeptDesigAndFinInstitution.aspx" class="btn btn-danger btn-block text-center">Cancel</a>
                            <%--<asp:Button ID="btnDeptCancel" OnClick="btnDeptCancel_Click" CssClass="btn btn-danger btn-block text-center" ClientIDMode="Static" runat="server" Text="Cancel" />--%>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container" id="divDesignationDetails" runat="server">
                <div class="row">
                    <div class="form-row">
                        <div class="form-group col-md-12 well well-sm">
                            <asp:Label ID="lbl_Desig_title" ClientIDMode="Static" CssClass="h3" runat="server" Text="Add New Designation"></asp:Label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="txtDesigName">Name</label>
                            <asp:TextBox CssClass="form-control" ID="txtDesigName" ClientIDMode="Static" runat="server"></asp:TextBox>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <asp:Button ID="btnDesigAdd" OnClick="btnDesigAdd_Click" CssClass="btn btn-success btn-block text-center" ClientIDMode="Static" runat="server" Text="Add" />
                        </div>
                        <div class="form-group col-md-4">
                            <asp:Button ID="btnDesigClear" OnClientClick="clearTextBoxes('txtDesigName')" CssClass="btn btn-secondary btn-block text-center" ClientIDMode="Static" runat="server" Text="Clear" />
                        </div>
                        <div class="form-group col-md-4">
                            <a href="DeptDesigAndFinInstitution.aspx" class="btn btn-danger btn-block text-center">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container" id="divFinInstDetails" runat="server">
                <div class="row">
                    <div class="form-row">
                        <div class="form-group col-md-12 well well-sm">
                            <asp:Label ID="lbl_Fin_title" ClientIDMode="Static" CssClass="h3" runat="server" Text="Add New Financial Institution"></asp:Label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="txtFinInstName">Name</label>
                            <asp:TextBox CssClass="form-control" ID="txtFinInstName" ClientIDMode="Static" runat="server"></asp:TextBox>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="txtFinInstAddress">Address</label>
                            <asp:TextBox CssClass="form-control" ID="txtFinInstAddress" ClientIDMode="Static" runat="server"></asp:TextBox>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <asp:Button ID="btnFinInstAdd" CssClass="btn btn-success btn-block text-center" ClientIDMode="Static" OnClick="btnFinInstAdd_Click" runat="server" Text="Add" />
                        </div>
                        <div class="form-group col-md-4">
                            <asp:Button ID="btnFinInstClear" CssClass="btn btn-secondary btn-block text-center" ClientIDMode="Static" runat="server" OnClientClick="clearTextBoxes('txtFinInstAddress','txtFinInstName')" Text="Clear" />
                        </div>
                        <div class="form-group col-md-4">
                            <a href="DeptDesigAndFinInstitution.aspx" class="btn btn-danger btn-block text-center">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
        </div>
    </div>
</asp:Content>
