<%@ Page Title="Earning And Deductions" Language="C#" MasterPageFile="~/Salary.Master" AutoEventWireup="true" CodeBehind="EarningAndDeductions.aspx.cs" Inherits="NBU.PayBill.Salary.Earning" %>
<%@ Register Src="~/Controls/EarningAndDeductionDetails.ascx" TagPrefix="uc" TagName="ED_Details" %>
<%@ Register Src="~/Controls/Category.ascx" TagPrefix="uc" TagName="Category" %>
<%@ Register Src="~/Controls/Subcategory.ascx" TagPrefix="uc" TagName="Subcategory" %>
<asp:Content ID="HeadContent" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="MainContent" ContentPlaceHolderID="BodyContent" runat="server">
    <div class="panel panel-default">

        <div class="panel-heading">
            Display &nbsp
            <%--Dropdown list for Earning / Deduction--%>
            <asp:DropDownList AutoPostBack="true" ID="ddlEarningDeductions" runat="server" OnSelectedIndexChanged="ddlEarningDeductions_SelectedIndexChanged">
                <asp:ListItem Text="Earning" Value="E"></asp:ListItem>
                <asp:ListItem Text="Deduction" Value="D"></asp:ListItem>
            </asp:DropDownList>

            Category &nbsp
            <%--Dropdown list for Category--%>
            <asp:DropDownList AutoPostBack="true" ID="ddlCategories" runat="server">
            </asp:DropDownList>

            Subcategories &nbsp
            <%--Dropdown list for Subcategories--%>
            <asp:DropDownList AutoPostBack="true" ID="ddlSubcategories" runat="server">
            </asp:DropDownList>

            &nbsp &nbsp &nbsp
            <%--Button for displaying earnings and deductions--%>
            <asp:Button CssClass="btn btn-danger" ID="btnDisplayData" runat="server" Text="Show All" />

        </div>
        <div class="panel-body">

            <%-- Grid view for displaying data --%>
            <asp:GridView ID="gvEarningDeduction" runat="server" AutoGenerateColumns="false" AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true">
                <HeaderStyle CssClass="gvHeader" HorizontalAlign="Center" VerticalAlign="Middle" />
                <RowStyle CssClass="gvRows" HorizontalAlign="Left" VerticalAlign="Middle" />
                <Columns>
                    <asp:TemplateField HeaderText="Type" >
                        <ItemTemplate>
                            <asp:Label ID="lblType" runat="server" Text=""></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Category" >
                        <ItemTemplate>
                            <asp:Label ID="lblCategory" runat="server" Text=""></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Subcategory" >
                        <ItemTemplate>
                            <asp:Label ID="lblSubcategory" runat="server" Text=""></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Name" >
                        <ItemTemplate>
                            <asp:Label ID="lblName" runat="server" Text=""></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>

        </div>
        <div class="panel-footer">
            <%--Label for No Records Found--%>
            <asp:Label ID="lblNoRecordsFound" runat="server" Text=""></asp:Label>
            <br />
            <a href="#addEarningForm" class="btn btn-primary" rel="modal:open"> + Add New Earning </a>
            <a href="#addDeductionForm" class="btn btn-primary" rel="modal:open"> + Add New Deduction </a>
            <a href="#addCategoryForm" class="btn btn-primary" rel="modal:open"> + Add New Category </a>
            <a href="#addSubcategoryForm" class="btn btn-primary" rel="modal:open"> + Add New Subcategory </a>
        </div>
    </div>
    <div class="modal" id="addEarningForm">
        <uc:ED_Details ID="UCaddEarningForm" ClientIDMode="Static" runat="server"/>
    </div>
    <div class="modal" id="addDeductionForm">
        <uc:ED_Details ID="UCaddDeductionForm" ClientIDMode="Static" runat="server"/>
    </div>
    <div class="modal" id="addCategoryForm">
        <uc:Category ID="UCaddCategories" ClientIDMode="Static" runat="server" />
    </div>
    <div class="modal" id="addSubcategoryForm">
        <uc:Subcategory ID="UCaddSubcategories" ClientIDMode="Static" runat="server" />
    </div>
</asp:Content>
